[package]
name = "solana-program-subaccount"
description = "Solana Subaccount and related definitions."
version = "3.0.0"
repository = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

# [package.metadata.docs.rs]
# targets = ["x86_64-unknown-linux-gnu"]
# all-features = true
# rustdoc-args = ["--cfg=docsrs"]

[dependencies]
solana-address = { workspace = true }
solana-account-info = { workspace = true }
solana-define-syscall = { workspace = true }
solana-program-entrypoint = { workspace = true }
solana-program-error = { workspace = true }
# solana-program-memory = { workspace = true }

# [dev-dependencies]
# solana-address = { workspace = true, features = ["atomic"] }

[lints]
workspace = true
